AWSTemplateFormatVersion: '2010-09-09'
Description: 'Password Manager IAM User Setup'

Parameters:
  UserName:
    Type: String
    Default: password-manager-user
    Description: IAM user name for Password Manager

Resources:
  PasswordManagerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      Path: "/password-manager/"

  PasswordManagerAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref PasswordManagerUser
      Status: Active

  PasswordManagerCredentials:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub '/password-manager/${UserName}/credentials'
      Type: SecureString
      Value: !Sub '{"accessKeyId":"${PasswordManagerAccessKey}","secretAccessKey":"${PasswordManagerAccessKey.SecretAccessKey}"}'

  PasswordManagerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: password-manager-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:GetParameter
              - ssm:DeleteParameter
            Resource: !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/password-manager/*'
      Users:
        - !Ref PasswordManagerUser

Outputs:
  ParameterName:
    Description: Name of the parameter containing the credentials
    Value: !Ref PasswordManagerCredentials