AWSTemplateFormatVersion: '2010-09-09'
Description: 'Password Manager IAM User Setup'

Parameters:
  UserName:
    Type: String
    Default: password-manager-user
    Description: IAM user name for Password Manager

Resources:
  PasswordManagerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      Path: "/password-manager/"

  PasswordManagerAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref PasswordManagerUser
      Status: Active

  PasswordManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '/password-manager/${UserName}/credentials'
      Description: 'Credentials for Password Manager IAM User'
      SecretString: !Sub '{"accessKeyId":"${PasswordManagerAccessKey}","secretAccessKey":"${PasswordManagerAccessKey.SecretAccessKey}"}'

  PasswordManagerPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: password-manager-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:GetParameter
              - ssm:GetParametersByPath
              - ssm:DeleteParameter
            Resource: !Sub 'arn:aws:ssm:*:${AWS::AccountId}:parameter/password-manager/*'
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:PutSecretValue
              - secretsmanager:UpdateSecret
              - secretsmanager:DeleteSecret
            Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/password-manager/*'
      Users:
        - !Ref PasswordManagerUser

Outputs:
  SecretArn:
    Description: ARN of the secret containing the credentials
    Value: !Ref PasswordManagerSecret